# Build a standalone Windows executable of Comet and package it as a zip.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\build-windows.ps1
#
# Optional environment variables:
#   COMET_RELEASE_TAG   If set, also creates/updates a GitHub release on the
#                       `fork` remote with the zip as asset (requires gh CLI).
#   FASTAPI_TEST_PORT   Port used for the smoke test (default: 8020).

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

Write-Host "== Comet Windows build ==" -ForegroundColor Cyan

# --- 0. Prerequisites --------------------------------------------------------
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Error "uv is not installed. Run scripts\setup-windows.ps1 first."
}
if (-not (Test-Path ".venv")) {
    Write-Host "Creating virtualenv..." -ForegroundColor Yellow
    uv sync
}

# Ensure PyInstaller is available in the venv.
$pyinstaller = uv pip list 2>$null | Select-String "^pyinstaller\s"
if (-not $pyinstaller) {
    Write-Host "Installing PyInstaller..." -ForegroundColor Yellow
    uv pip install pyinstaller
}

# --- 1. Clean previous builds -------------------------------------------------
Remove-Item "build", "dist" -Recurse -Force -ErrorAction SilentlyContinue

# --- 2. Build -----------------------------------------------------------------
Write-Host "Building executable (this takes a few minutes)..." -ForegroundColor Yellow
uv run pyinstaller comet.spec --noconfirm
if ($LASTEXITCODE -ne 0 -or -not (Test-Path "dist\comet\comet.exe")) {
    Write-Error "PyInstaller build failed."
}

# --- 3. Smoke test -------------------------------------------------------------
$testPort = if ($env:FASTAPI_TEST_PORT) { $env:FASTAPI_TEST_PORT } else { "8020" }
Write-Host "Smoke test on port $testPort..." -ForegroundColor Yellow

$env:FASTAPI_PORT = $testPort
$proc = Start-Process -FilePath "dist\comet\comet.exe" -PassThru -WindowStyle Hidden
try {
    $healthy = $false
    foreach ($i in 1..30) {
        Start-Sleep -Seconds 2
        try {
            $response = Invoke-WebRequest -Uri "http://127.0.0.1:$testPort/health" `
                -UseBasicParsing -TimeoutSec 5
            if ($response.StatusCode -eq 200) { $healthy = $true; break }
        }
        catch { }
    }

    if (-not $healthy) {
        Write-Error "Smoke test failed: /health did not return 200 within 60s."
    }
    Write-Host "[OK] Smoke test passed: /health returned 200." -ForegroundColor Green
}
finally {
    Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
}

# Remove runtime data generated by the smoke test so the zip ships clean.
Remove-Item "dist\comet\data" -Recurse -Force -ErrorAction SilentlyContinue

# --- 4. Package -----------------------------------------------------------------
$commit = (git rev-parse --short HEAD)
$zipPath = "dist\comet-windows-x64-$commit.zip"
Compress-Archive -Path "dist\comet" -DestinationPath $zipPath -Force
$sizeMb = "{0:N1}" -f ((Get-Item $zipPath).Length / 1MB)
Write-Host "[OK] Packaged: $zipPath ($sizeMb MB)" -ForegroundColor Green

# --- 5. Optional GitHub release ---------------------------------------------------
if ($env:COMET_RELEASE_TAG) {
    if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
        Write-Warning "gh CLI not found; skipping release creation."
    }
    else {
        $tag = $env:COMET_RELEASE_TAG
        Write-Host "Publishing release $tag to dgartu/comet..." -ForegroundColor Yellow
        gh release create $tag --repo dgartu/comet `
            --title "Comet for Windows (x64) - $tag" `
            --notes "Standalone Windows build from commit $commit. Extract and run comet.exe." `
            $zipPath
        Write-Host "[OK] Release published." -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "== Build complete ==" -ForegroundColor Cyan
Write-Host "Executable: dist\comet\comet.exe"
